use std::fs;
use std::path::{Path, PathBuf};

use walkdir::WalkDir;

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));

    println!("cargo:rerun-if-changed=Cargo.toml");

    // --- Parse branding from Cargo.toml ---
    let cargo_toml_path = manifest_dir.join("Cargo.toml");
    let cargo_toml_contents =
        fs::read_to_string(&cargo_toml_path).expect("failed to read Cargo.toml");
    let cargo_toml: toml::Table =
        toml::from_str(&cargo_toml_contents).expect("failed to parse Cargo.toml");

    let branding = cargo_toml
        .get("package")
        .and_then(|p| p.get("metadata"))
        .and_then(|m| m.get("branding"))
        .expect("[package.metadata.branding] section missing from Cargo.toml");

    let command_name = branding
        .get("command_name")
        .and_then(toml::Value::as_str)
        .expect("branding.command_name missing");
    let project_dir = branding
        .get("project_dir")
        .and_then(toml::Value::as_str)
        .expect("branding.project_dir missing");
    let display_name = branding
        .get("display_name")
        .and_then(toml::Value::as_str)
        .expect("branding.display_name missing");

    println!("cargo:rustc-env=BRAND_COMMAND_NAME={command_name}");
    println!("cargo:rustc-env=BRAND_PROJECT_DIR={project_dir}");
    println!("cargo:rustc-env=BRAND_DISPLAY_NAME={display_name}");

    // --- Expand placeholders in src/artifacts/**/*.md and write to OUT_DIR ---
    let artifacts_dir = manifest_dir.join("src").join("artifacts");
    let out_artifacts_dir = out_dir.join("artifacts");

    for entry in WalkDir::new(&artifacts_dir)
        .into_iter()
        .filter_map(Result::ok)
        .filter(|e| e.file_type().is_file())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "md"))
    {
        let source_path = entry.path();
        let relative = source_path
            .strip_prefix(&artifacts_dir)
            .expect("artifact path should be under artifacts_dir");

        println!("cargo:rerun-if-changed={}", source_path.display());

        let contents = fs::read_to_string(source_path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", source_path.display()));

        let expanded = contents
            .replace("{{brand.command_name}}", command_name)
            .replace("{{brand.project_dir}}", project_dir)
            .replace("{{brand.display_name}}", display_name);

        let dest_path = out_artifacts_dir.join(relative);
        if let Some(parent) = dest_path.parent() {
            fs::create_dir_all(parent)
                .unwrap_or_else(|e| panic!("failed to create {}: {e}", parent.display()));
        }
        fs::write(&dest_path, expanded)
            .unwrap_or_else(|e| panic!("failed to write {}: {e}", dest_path.display()));
    }

    // Also emit rerun-if-changed for the artifacts directory itself so new files trigger rebuilds
    emit_rerun_for_dirs(&artifacts_dir);

    // --- Generate CLI help text with branding interpolation ---
    generate_cli_help(&out_dir, command_name, project_dir);
}

fn generate_cli_help(out_dir: &Path, cmd: &str, project_dir: &str) {
    let help = format!(
        r####"// Generated by build.rs — do not edit.
pub const ROOT_HELP_EXAMPLES: &str = "\
Example flows:\n\
  engineer:\n\
    {cmd} runtime setup --root . --team MET --project \"MetaStack CLI\"\n\
    {cmd} context scan --root .\n\
    {cmd} backlog plan --root . --request \"Break the next release into tickets\"\n\
\n\
  team lead:\n\
    {cmd} linear issues list --team MET --state \"In Progress\"\n\
    {cmd} dashboard team --team MET --project \"MetaStack CLI\"\n\
\n\
  ops operator:\n\
    {cmd} agents listen --team MET --project \"MetaStack CLI\"\n\
    {cmd} dashboard ops --root .";

pub const BACKLOG_HELP_EXAMPLES: &str = "\
Examples:\n\
  {cmd} backlog spec --root .\n\
  {cmd} backlog spec --root . --no-interactive --request \"Add a repo-local SPEC workflow\"\n\
  {cmd} backlog spec --root . --no-interactive --request \"Improve the current SPEC\" --answer \"Clarify the non-goals\"\n\
  {cmd} backlog plan --root . --request \"Split the onboarding work into tickets\"\n\
  {cmd} backlog plan --root . ENG-10144\n\
  {cmd} backlog plan --root . ENG-10144 --velocity\n\
  {cmd} backlog improve --root . --mode basic\n\
  {cmd} backlog improve --root . ENG-10144 --mode advanced --apply\n\
  {cmd} backlog tech MET-35\n\
  {cmd} backlog split MET-35\n\
  {cmd} backlog sync status\n\
  {cmd} backlog sync link MET-35 --entry manual-notes --pull\n\
  {cmd} backlog sync pull --all\n\
  {cmd} backlog sync push MET-35 --update-description";

pub const BACKLOG_IMPROVE_HELP: &str = "\
Use `{cmd} backlog improve` for a repo-scoped backlog sweep across existing issues in one state.\n\
Choose `--mode basic` for conservative metadata hygiene and `--mode advanced` for deeper\n\
rewrites or parent-child structure proposals.\n\
\n\
Use `{cmd} linear issues refine` when you already know which issue needs a critique/rewrite and\n\
the primary goal is improving that issue's description rather than scanning the backlog.";

pub const ISSUES_REFINE_HELP: &str = "\
Use `{cmd} linear issues refine` when you already know which issue needs a critique/rewrite and\n\
want a focused description-quality pass with auditable refinement artifacts.\n\
\n\
Use `{cmd} backlog improve` when you want a repo-scoped backlog sweep for missing labels,\n\
acceptance criteria, priority/estimate, and parent-child structure opportunities.";

pub const AGENTS_HELP_EXAMPLES: &str = "\
Examples:\n\
  {cmd} agents listen --team MET --project \"MetaStack CLI\"\n\
  {cmd} agents execute MET-45 --team MET --project \"MetaStack CLI\"\n\
  {cmd} agents execute MET-45 --root . --max-turns 10\n\
  {cmd} agents review 42 --root .\n\
  {cmd} agents review 42 --root . --dry-run\n\
  {cmd} agents review --root .\n\
  {cmd} agents review --root . --check\n\
  {cmd} agents review --root . --once\n\
  {cmd} agents retro 42 --root .\n\
  {cmd} agents retro --root .\n\
  {cmd} agents improve --root .\n\
  {cmd} agents improve --root . --render-once\n\
  {cmd} agents workflows list --root .\n\
  {cmd} agents workflows run ticket-implementation --root .\n\
  {cmd} agents workflows run ticket-implementation --root . --no-interactive --param issue=MET-93\n\
  {cmd} agents workflows run ticket-implementation --root . --render-once --param issue=MET-93";

pub const WORKFLOW_RUN_HELP: &str = "\
Interactive mode:\n\
  TTY runs open a guided wizard, then land on a review/export dashboard.\n\
  Use --render-once for deterministic wizard snapshots in tests.\n\
  Use --events to script render-once snapshots through review, edit, and save states.\n\
  Use accept-edit/discard-edit to prove edit outcomes, and paste=TEXT to inject scripted input.\n\
\n\
Non-interactive mode:\n\
  Use --no-interactive with explicit --param key=value pairs for scripts and CI.\n\
  Runs without a TTY use the same fallback automatically unless --render-once is set.\n\
  Use --output and --overwrite to save the reviewed Markdown artifact headlessly.";

pub const LISTEN_HELP_EXAMPLES: &str = "\
Interactive dashboard:\n\
  - The dashboard has two primary panes: Agent Sessions and In Progress Issues - All Users (from Linear)\n\
  - Tab switches focus between panes; Left/Right switches Active/Completed views within Agent Sessions\n\
  - In Progress Issues rows show short title, assignee, and open-PR indicator for each In Progress issue\n\
  - Press Enter on a selected item to open its detail pane; Esc or Backspace closes it\n\
  - Session detail includes milestones, references, prompt context, log excerpts, and PR info\n\
  - In Progress Issue detail shows the issue description, assignee, PR URL, and Linear link\n\
  - Use Up/Down (or j/k in vim mode) to navigate, PgUp/PgDn to scroll detail content\n\
  - Press P to pause a running session, R to resume a paused session or retry a blocked one\n\
  - Use --hide-active-issues or --hide-preview to simplify the dashboard layout\n\
  - Configure defaults in {project_dir}/meta.json under listen.dashboard_active_issues and listen.dashboard_preview\n\
\n\
Terminal-only examples:\n\
  {cmd} agents listen --check --root .\n\
  {cmd} agents listen --team MET --once\n\
  {cmd} listen sessions list\n\
\n\
Concurrent project-scoped examples from one checkout:\n\
  {cmd} agents listen --team MET --project \"MetaStack CLI\"\n\
  {cmd} agents listen --team MET --project \"MetaStack API\"\n\
  {cmd} listen sessions inspect --root . --project \"MetaStack API\"\n\
  {cmd} listen sessions clear --root . --project \"MetaStack API\"\n\
  {cmd} listen sessions resume --root . --project \"MetaStack API\" --once\n\
\n\
Default-project example:\n\
  {cmd} runtime setup --root . --team MET --project \"MetaStack CLI\"\n\
  {cmd} agents listen --team MET";

pub const CONTEXT_HELP_EXAMPLES: &str = "\
Examples:\n\
  {cmd} context show --root .\n\
  {cmd} context scan --root .\n\
  {cmd} context doctor --root .";

pub const RUNTIME_HELP_EXAMPLES: &str = "\
Examples:\n\
  {cmd} runtime config --json\n\
  {cmd} runtime setup --root . --team MET --project \"MetaStack CLI\"\n\
  {cmd} runtime cron status --root .";

pub const RUNTIME_CONFIG_HELP: &str = "\
Resolution precedence for built-in provider/model/reasoning:\n\
  1. explicit CLI overrides such as --agent/--provider, --model, and --reasoning\n\
  2. command route override\n\
  3. family route override\n\
  4. repo defaults from `{cmd} runtime setup`\n\
  5. install defaults from `{cmd} runtime config`\n\
\n\
Built-in provider catalog:\n\
  codex: gpt-5.4, gpt-5.3-codex, gpt-5.2-codex, gpt-5.1-codex-max, gpt-5.1-codex,\n\
         gpt-5.1-codex-mini, gpt-5-codex, gpt-5-codex-mini\n\
         reasoning: low, medium, high\n\
  claude: sonnet, opus, haiku, sonnet[1m], opusplan\n\
          reasoning: low, medium, high, max\n\
\n\
Confirm the effective selection before launch:\n\
  {cmd} agents workflows run ticket-implementation --root . --dry-run";

pub const RUNTIME_SETUP_HELP: &str = "\
Repo defaults written by `{cmd} runtime setup` participate in the built-in resolution order:\n\
  explicit CLI override -> command route -> family route -> repo default -> install default\n\
\n\
Built-in provider/model/reasoning combinations are validated before they are saved.\n\
Use `{cmd} agents workflows run ... --dry-run` or `{cmd} context scan --root .` to confirm the\n\
resolved provider, model, reasoning, route key, and config source before or during execution.\n\
\n\
Listen prerequisites:\n\
  codex: `~/.codex/config.toml` must set `approval_policy = \"never\"`\n\
         and `sandbox_mode = \"danger-full-access\"`, and Linear MCP should be removed or\n\
         disabled with `-c mcp_servers.linear.enabled=false`\n\
  claude: `claude` must be on PATH and `ANTHROPIC_API_KEY` should be unset\n\
  verify: `{cmd} agents listen --check --root .`";

pub const DASHBOARD_HELP_EXAMPLES: &str = "\
Examples:\n\
  {cmd} dashboard linear --team MET --project \"MetaStack CLI\"\n\
  {cmd} dashboard agents --team MET --project \"MetaStack CLI\" --render-once\n\
  {cmd} dashboard team --team MET\n\
  {cmd} dashboard ops --root .";

pub const MERGE_HELP_EXAMPLES: &str = "\
Examples:\n\
  {cmd} merge --json\n\
  {cmd} merge\n\
  {cmd} merge --render-once --events space,down,space,enter\n\
  {cmd} merge --no-interactive --pull-request 101 --pull-request 102 --validate \"make quality\"";

pub const WORKSPACE_HELP_EXAMPLES: &str = "\
Examples:\n\
  {cmd} workspace list --root .\n\
  {cmd} workspace clean ENG-10175 --root .\n\
  {cmd} workspace clean --target-only --root .\n\
  {cmd} workspace prune --dry-run --root .";

pub const UPGRADE_HELP_EXAMPLES: &str = "\
Default latest-stable path:\n\
  {cmd} upgrade --check\n\
  {cmd} upgrade --dry-run\n\
  {cmd} upgrade\n\
\n\
Advanced version-management path:\n\
  {cmd} upgrade --version 0.2.0 --dry-run\n\
  {cmd} upgrade --version 0.3.0-rc.1 --prerelease\n\
  {cmd} upgrade --version 0.1.0 --allow-downgrade";
"####,
        cmd = cmd,
        project_dir = project_dir,
    );

    let dest = out_dir.join("cli_help.rs");
    fs::write(&dest, help).unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}

fn emit_rerun_for_dirs(dir: &Path) {
    if !dir.is_dir() {
        return;
    }
    println!("cargo:rerun-if-changed={}", dir.display());
    for entry in fs::read_dir(dir).into_iter().flatten().flatten() {
        if entry.file_type().is_ok_and(|t| t.is_dir()) {
            emit_rerun_for_dirs(&entry.path());
        }
    }
}
