use std::path::{Path, PathBuf};

use anyhow::Result;

use crate::backlog::template_seed_files;
use crate::cli::ScaffoldArgs;
use crate::fs::{
    FileWriteStatus, PlanningPaths, canonicalize_existing_dir, display_path, ensure_dir,
    write_text_file,
};

#[derive(Debug, Clone)]
pub struct ScaffoldReport {
    root: PathBuf,
    created_dirs: Vec<String>,
    created_files: Vec<String>,
    updated_files: Vec<String>,
    reused_paths: Vec<String>,
}

impl ScaffoldReport {
    pub fn render(&self) -> String {
        let mut lines = vec![format!(
            "Scaffolded MetaStack workspace at {}",
            self.root.display()
        )];
        append_section(&mut lines, "Created directories", &self.created_dirs);
        append_section(&mut lines, "Created files", &self.created_files);
        append_section(&mut lines, "Updated files", &self.updated_files);
        append_section(&mut lines, "Reused paths", &self.reused_paths);
        lines.join("\n")
    }
}

pub fn run_scaffold(args: &ScaffoldArgs) -> Result<ScaffoldReport> {
    let root = canonicalize_existing_dir(&args.root)?;
    ensure_layout(&root, args.force, true)
}

pub fn ensure_planning_layout(root: &Path, force: bool) -> Result<()> {
    let _ = ensure_layout(root, force, true)?;
    Ok(())
}

fn ensure_layout(root: &Path, force: bool, include_cron: bool) -> Result<ScaffoldReport> {
    let paths = PlanningPaths::new(root);
    migrate_legacy_agent_layout(&paths)?;
    let mut report = ScaffoldReport {
        root: root.to_path_buf(),
        created_dirs: Vec::new(),
        created_files: Vec::new(),
        updated_files: Vec::new(),
        reused_paths: Vec::new(),
    };

    let mut dirs = vec![
        &paths.metastack_dir,
        &paths.agent_dir,
        &paths.agent_briefs_dir,
        &paths.agent_sessions_dir,
        &paths.backlog_dir,
        &paths.codebase_dir,
        &paths.workflows_dir,
    ];
    if include_cron {
        dirs.push(&paths.cron_dir);
    }

    for dir in dirs {
        if ensure_dir(dir)? {
            report.created_dirs.push(display_path(dir, root));
        } else {
            report.reused_paths.push(display_path(dir, root));
        }
    }

    for (path, contents) in templates(&paths, include_cron)
        .into_iter()
        .chain(template_seed_files(&paths).into_iter())
    {
        match write_text_file(&path, &contents, force)? {
            FileWriteStatus::Created => report.created_files.push(display_path(&path, root)),
            FileWriteStatus::Updated => report.updated_files.push(display_path(&path, root)),
            FileWriteStatus::Unchanged => report.reused_paths.push(display_path(&path, root)),
        }
    }

    Ok(report)
}

pub fn ensure_backlog_templates(root: &Path, force: bool) -> Result<()> {
    ensure_planning_layout(root, false)?;

    let paths = PlanningPaths::new(root);
    ensure_dir(&paths.backlog_template_dir)?;

    for (path, contents) in template_seed_files(&paths) {
        let _ = write_text_file(&path, &contents, force)?;
    }

    Ok(())
}

fn append_section(lines: &mut Vec<String>, title: &str, entries: &[String]) {
    if entries.is_empty() {
        return;
    }

    lines.push(format!("{title}:"));
    for entry in entries {
        lines.push(format!("  - {entry}"));
    }
}

fn templates(paths: &PlanningPaths, include_cron: bool) -> Vec<(PathBuf, String)> {
    let metastack_readme = format!(
        r#"# MetaStack Workspace

This directory stores repo-local MetaStack state generated by `metastack-cli`.

- `meta.json` stores repo-scoped defaults such as the Linear team and project ID.
- `backlog/` holds team task drafts and reusable backlog templates.
- `backlog/_TEMPLATE/` stores the repo-local backlog template used by `meta plan` and `meta backlog tech`.
- `agents/briefs/` stores deterministic kickoff prompts created by `meta agents kickoff`.
- `agents/sessions/` stores repo-local agent logs such as `meta scan`; MetaListen session state is
  stored in the install-scoped MetaStack data root keyed by the canonical source `.metastack` root.
- `codebase/` holds generated repository context for future agents.{}
- `workflows/` stores repo-local workflow playbooks consumed by `meta workflows`.

Typical flow:

1. Run `meta scaffold`
2. Run `meta config`
3. Run `meta setup`
4. Run `meta scan`
5. Run `meta agents kickoff --ticket <ID>`
6. Run `meta listen`
"#,
        if include_cron {
            "\n- `cron/` stores Markdown cron jobs plus repo-local scheduler runtime state."
        } else {
            ""
        }
    );

    let mut templates = vec![
        (
            paths.meta_path(),
            r#"{
  "linear": {
    "team": null,
    "project_id": null
  }
}
"#
            .to_string(),
        ),
        (paths.metastack_dir.join("README.md"), metastack_readme),
        (
            paths.agent_dir.join("README.md"),
            r#"# Agent Workspace

Use this directory for reusable agent artifacts generated by `metastack-cli`.

- `briefs/` stores deterministic kickoff prompts created by `meta agents kickoff`.
- `sessions/` stores repo-local agent logs such as `meta scan`; MetaListen session state and logs
  are stored in the install-scoped MetaStack data root.
"#
            .to_string(),
        ),
        (
            paths.backlog_dir.join("README.md"),
            r#"# Backlog

Use this directory for local backlog notes, synced Linear issue files, and generated technical issue drafts.

- `_TEMPLATE/` stores the canonical repo-local backlog template expanded by `meta plan` and `meta backlog tech`.
- `<ISSUE>/` directories store synced backlog issue files and generated technical drafts.
"#
            .to_string(),
        ),
        (
            paths.codebase_dir.join("README.md"),
            r#"# Codebase Context

Generated context files live here:

- `SCAN.md`
- `ARCHITECTURE.md`
- `CONCERNS.md`
- `CONVENTIONS.md`
- `INTEGRATIONS.md`
- `STACK.md`
- `STRUCTURE.md`
- `TESTING.md`

`meta scan` refreshes `SCAN.md` directly, then asks the configured local agent to author the higher-level context docs.
"#
            .to_string(),
        ),
        (
            paths.workflows_dir.join("README.md"),
            r#"# Workflow Playbooks

`meta workflows` loads repo-local playbooks from this directory in addition to the built-in workflow set.

Playbooks use Markdown files with YAML front matter:

```md
---
name: release-triage
summary: Investigate a release blocker and propose next actions.
provider: codex
parameters:
  - name: incident
    description: Human-readable incident summary.
    required: true
validation:
  - Confirm impact, scope, and current owner.
instructions: |
  Keep the report concise and action-oriented.
---
Incident summary:
{{incident}}
```

Supported front matter keys:

- `name`: unique workflow identifier used by `meta workflows explain|run`
- `summary`: one-line description shown by `meta workflows list`
- `provider`: default local agent/provider name used for `run`
- `parameters`: input contract with `name`, `description`, optional `required`, and optional `default`
- `validation`: checklist items injected into explain/run output
- `instructions`: optional agent instructions rendered separately from the main prompt
- `linear_issue_parameter`: optional parameter name whose value should be resolved from Linear before prompt rendering

Prompt templates can reference workflow parameters plus shared variables such as:

- `{{repo_root}}`
- `{{workflow_contract}}` for the full injected workflow contract, repo scope block, repo overlays, and repo-scoped instructions
- `{{effective_instructions}}` for only the optional repo-scoped instructions file from `.metastack/meta.json`
- `{{project_rules}}` for only repo overlay content from `AGENTS.md` and legacy `WORKFLOW.md`
- `{{context_bundle}}`
- `{{repo_map}}`
- `{{validation_steps}}`
- `{{issue_identifier}}`, `{{issue_title}}`, `{{issue_url}}`, `{{issue_state}}`, `{{issue_description}}` when `linear_issue_parameter` is set
"#
            .to_string(),
        ),
    ];

    if include_cron {
        templates.push((
            paths.cron_readme_path(),
            r#"# Cron Jobs

Use this directory for repository-local automation jobs managed by `meta cron`.

- One Markdown file per job, such as `nightly.md`
- YAML front matter stores the schedule and command metadata
- Markdown body stores operator notes and future-agent context
- `.runtime/` is created on demand for PID files, logs, and scheduler state
"#
            .to_string(),
        ));
    }

    templates
}

fn migrate_legacy_agent_layout(paths: &PlanningPaths) -> Result<()> {
    for (legacy, canonical) in [
        (paths.legacy_agent_dir(), paths.agent_dir.clone()),
        (
            paths.legacy_agent_briefs_dir(),
            paths.agent_briefs_dir.clone(),
        ),
        (
            paths.legacy_agent_sessions_dir(),
            paths.agent_sessions_dir.clone(),
        ),
    ] {
        if !legacy.exists() || canonical.exists() {
            continue;
        }

        if std::fs::rename(&legacy, &canonical).is_ok() {
            continue;
        }

        if legacy.is_file() {
            std::fs::copy(&legacy, &canonical).map(|_| ())?;
        } else {
            copy_dir_contents(&legacy, &canonical)?;
        }
    }

    Ok(())
}

fn copy_dir_contents(source: &Path, destination: &Path) -> Result<()> {
    ensure_dir(destination)?;
    for entry in std::fs::read_dir(source)? {
        let entry = entry?;
        let source_path = entry.path();
        let destination_path = destination.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            copy_dir_contents(&source_path, &destination_path)?;
        } else {
            if let Some(parent) = destination_path.parent() {
                ensure_dir(parent)?;
            }
            std::fs::copy(&source_path, &destination_path)?;
        }
    }

    Ok(())
}
